### ISSUE TITLE
Error in export_2hlayers_model.py InvalidArgumentError: Cannot assign a device for operation private-input/encode/mul

### ISSUE THREAD

**Issue by kamathhrishi** [tf-encrypted/tf-encrypted#400] opened 2019-02-12 01:55 UTC
I ran the export_2hlayers_model.py example and got this error. I ran it on a Macbook pro CPU.

Complete error goes like 

 ```
 File "<ipython-input-24-adaa386ad418>", line 1, in <module>
    runfile('/Users/hrishikesh/Hrishikesh/Projects/tf-encrypted/examples/export_2hlayers_model.py', wdir='/Users/hrishikesh/Hrishikesh/Projects/tf-encrypted/examples')

  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/hrishikesh/Hrishikesh/Projects/tf-encrypted/examples/export_2hlayers_model.py", line 47, in <module>
    sess.run(tf.global_variables_initializer())

  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)

  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)

  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)

  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Cannot assign a device for operation private-input/encode/mul: Operation was explicitly assigned to /job:localhost/replica:0/task:0/device:CPU:3 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[node private-input/encode/mul (defined at /Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tf_encrypted/protocol/pond.py:530)  = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:3"](private-input/Const, private-input/encode/mul/y)]]

Caused by op 'private-input/encode/mul', defined at:
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/spyder/utils/ipython/start_kernel.py", line 245, in <module>
    main()
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/spyder/utils/ipython/start_kernel.py", line 241, in main
    kernel.start()
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-84f822066520>", line 1, in <module>
    runfile('/Users/hrishikesh/Hrishikesh/Projects/Private Machine Learning/tfencrypted/Get_Dataset.py', wdir='/Users/hrishikesh/Hrishikesh/Projects/Private Machine Learning/tfencrypted')
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/Users/hrishikesh/Hrishikesh/Projects/Private Machine Learning/tfencrypted/Get_Dataset.py", line 4, in <module>
    from convert import encode
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hrishikesh/Hrishikesh/Projects/Private Machine Learning/tfencrypted/convert.py", line 62, in <module>
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tf_encrypted/convert/convert.py", line 56, in convert
    x = self.protocol.define_private_input(input_player, item)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tf_encrypted/protocol/pond.py", line 452, in define_private_input
    output = helper(v)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tf_encrypted/protocol/pond.py", line 431, in helper
    w = self._encode(v, apply_scaling)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tf_encrypted/protocol/pond.py", line 530, in _encode
    scaled = rationals * self.fixedpoint_config.scaling_factor
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 878, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5042, in mul
    "Mul", x=x, y=y, name=name)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation private-input/encode/mul: Operation was explicitly assigned to /job:localhost/replica:0/task:0/device:CPU:3 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[node private-input/encode/mul (defined at /Users/hrishikesh/anaconda3/envs/tfencrypt/lib/python3.6/site-packages/tf_encrypted/protocol/pond.py:530)  = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:3"](private-input/Const, private-input/encode/mul/y)]]
```

**Comment by justin1121** [comment] 2019-02-12 14:30
Hi @kamathhrishi,

I think I've seen errors like this if running with tensorflow eager mode enabled. I assume that's probably not getting enabled somehow but can you confirm? Also what version of tensorflow are you using? I'd recommend using tensorflow 1.12.0 if possible.

Another thing I noticed is that you're running in an ipython shell. Maybe it's possible this shell is restricting access to all of the CPUs available. As it's saying it can't find `/job:localhost/replica:0/task:0/device:CPU:3`.

**Comment by kamathhrishi** [comment] 2019-02-13 01:31
I got this issue resolved. Not really sure why and how since all I did was remove my conda environment and create it again with tensorflow 1.12

**Comment by avitalsh** [comment] 2019-04-25 09:14
@justin1121 Hey, I get the same error. I use virtualenv. 
tensorflow eager mode is not enabled and I tried changing tf version from 1.13.1 to 1.12.0 but it didn't solve it. 
Do you have any idea of what else can be the issue?

**Comment by justin1121** [comment] 2019-04-25 12:27
Hey @avitalsh can you send your exact error output? Could be something slightly different. Thanks.

**Comment by avitalsh** [comment] 2019-04-25 14:01
@justin1121 this is what I get (after changing to tf 1.12.0)

Traceback (most recent call last):
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _run_fn
    self._extend_graph()
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1352, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation private-input/encode/mul: Operation was explicitly assigned to /job:tfe/replica:0/task:4/device:CPU:0 but available devices are [ /job:tfe/replica:0/task:0/device:CPU:0, /job:tfe/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
         [[{{node private-input/encode/mul}} = Mul[T=DT_FLOAT, _device="/job:tfe/replica:0/task:4/device:CPU:0"](private-input/api/0, private-input/encode/mul/y)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmarking.py", line 120, in <module>
    time_a = test_enc_time(model)
  File "benchmarking.py", line 104, in test_enc_time
    s_model.private_predict(np.zeros((1, 28, 28, 1)))
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/private_model.py", line 20, in private_predict
    sess.run(tf.global_variables_initializer())
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/session.py", line 110, in run
    feed_dict=feed_dict
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation private-input/encode/mul: Operation was explicitly assigned to /job:tfe/replica:0/task:4/device:CPU:0 but available devices are [ /job:tfe/replica:0/task:0/device:CPU:0, /job:tfe/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
         [[node private-input/encode/mul (defined at /cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/protocol/pond.py:541)  = Mul[T=DT_FLOAT, _device="/job:tfe/replica:0/task:4/device:CPU:0"](private-input/api/0, private-input/encode/mul/y)]]

Caused by op 'private-input/encode/mul', defined at:
  File "benchmarking.py", line 120, in <module>
    time_a = test_enc_time(model)
  File "benchmarking.py", line 99, in test_enc_time
    s_model = secure_model(model)
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/private_model.py", line 70, in secure_model
    y = c.convert(remove_training_nodes(graph_def), tfe.convert.register(), 'input-provider', inputs)
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/convert/convert.py", line 79, in convert
    x = self.protocol.define_private_input(input_player, item)
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/protocol/pond.py", line 459, in define_private_input
    output = helper(v)
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/protocol/pond.py", line 437, in helper
    tf_int_type=factory.native_type))
  File "/cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/protocol/pond.py", line 541, in _encode
    scaled = rationals * self.fixedpoint_config.scaling_factor
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 878, in binary_op_wrapper
    return func(x, y, name=name)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5042, in mul
    "Mul", x=x, y=y, name=name)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/cs/labs/peleg/avitalsh/virtualenvs/python3-dev-cpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation private-input/encode/mul: Operation was explicitly assigned to /job:tfe/replica:0/task:4/device:CPU:0 but available devices are [ /job:tfe/replica:0/task:0/device:CPU:0, /job:tfe/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
         [[node private-input/encode/mul (defined at /cs/labs/peleg/avitalsh/tools/tf-encrypted/tf_encrypted/protocol/pond.py:541)  = Mul[T=DT_FLOAT, _device="/job:tfe/replica:0/task:4/device:CPU:0"](private-input/api/0, private-input/encode/mul/y)]]

**Comment by justin1121** [comment] 2019-04-25 16:34
@avitalsh I'm stumped! If you'd be willing to share your code that could be helpful. @mortendahl do you have any ideas on what this could be?

**Comment by jvmancuso** [comment] 2019-04-25 18:33
it looks like this is slightly different than the original bug for this issue -- there it looked the problem was conflicting devices, this looks more like it's at the task level.  the original code would definitely help to investigate further

**Comment by mortendahl** [comment] 2019-04-25 19:40
Mirror @justin1121 and @jvmancuso, would be great to see the code you're running! Could it be that you're using a `tf.Session` instead of a `tfe.Session`?

**Comment by avitalsh** [comment] 2019-04-27 19:22
@justin1121 @jvmancuso @mortendahl 
I found the problem - I was running each server using a script that first wrote it's IP address to the config.json file and then started the tfe server. The problem was that I didn't wait untill everyone else finished writing to the config file to start the servers.

I do have a different problem now, which probably belong to a different issue - my code works fine when using local config, but when I change to remote config and run the exact same code -  its not working anymore.

**Comment by mortendahl** [comment] 2019-05-07 09:16
Closing up; second problem was addresses and fixed in https://github.com/tf-encrypted/tf-encrypted/issues/457.

**Closed by mortendahl** 2019-05-07 09:16 UTC
Labels: bug
