### ISSUE TITLE
Mixing protocols

### ISSUE THREAD

**Issue by avitalsh** [tf-encrypted/tf-encrypted#435] opened 2019-04-18 09:08 UTC
Hi,

Is there a way to use both protocols?
I would like to build a model that uses both the real ReLU (securenn protocol) and the approximated ReLU (pond protocol). Is this possible?

Thanks

**Comment by mortendahl** [comment] 2019-04-23 10:18
Hi @avitalsh, great question, and thanks for reaching out!

This is indeed possible, and there's a [better API](https://github.com/tf-encrypted/tf-encrypted/issues/402#issuecomment-468674197) for this in the pipeline:

```python
x = tfe.define_private_variable(tf.constant([1,2,3,4]))
y = tfe.define_private_variable(tf.constant([1,2,3,4]))

tfe.set_protocol(tfe.protocol.Pond())
approx = tfe.relu(x)
    
tfe.set_protocol(tfe.protocol.SecureNN())
exact = tfe.relu(y)
```

Note however that due to [a bug](https://github.com/tf-encrypted/tf-encrypted/issues/438) you'll get unexpected behaviour if you eg apply different relus to the same value as in the following:

```python
x = tfe.define_private_variable(tf.constant([1,2,3,4]))

tfe.set_protocol(tfe.protocol.Pond())
approx = tfe.relu(x)
    
tfe.set_protocol(tfe.protocol.SecureNN())
exact = tfe.relu(x)
```

We should have a fix for this in the coming days.

**Comment by mortendahl** [comment] 2019-04-23 10:23
Also, feel free to join [our slack](https://join.slack.com/t/tf-encrypted/shared_invite/enQtNjA0NDE2MDAxOTA2LTRjMWUwYWM3NTQ4MTk4NDNiOWI4Y2VjNDI5MDBhZDc5Y2RmNWMyODYyNDQ4MzMyMGM0YjZhZDYwMmJmNGJhYmE) if we can help!

**Closed** 2020-02-24 12:06 UTC
Labels: bug
