### ISSUE TITLE
Update examples to use Keras where possible

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#416] opened 2019-04-01 14:03 UTC

**Comment by jvmancuso** [comment] 2019-04-01 15:20
We should consider waiting on this until we finish refactoring the converter, unless we can do it with the current converter (related https://github.com/mortendahl/tf-encrypted/issues/297)

**Comment by mortendahl** [comment] 2019-04-02 09:51
Not sure I follow. Most of the examples are not using the converter.

**Comment by ianlivingstone** [comment] 2019-06-24 15:35
Duplicate of #541

**Closed** 2019-06-24 15:35 UTC
